name: daily-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        # You may pin to the exact commit or the version.
        # uses: dailydotdev/action-devcard@276972279623d2d6dd68aef668fdb75adb3a9d19
        uses: dailydotdev/action-devcard@3.2.1
        with:
          # Your daily.dev user id
          user_id: ${{ secrets.USER_ID }}
          # GitHub Token used to commit the devcard
          token: ${{ github.token }}
          # Branch used to commit the devcard
          commit_branch: main
          # Commit message
          # commit_message: "Update ${filename}"
          # Filename to save devcard to
          commit_filename: "devcard.png"
          # Committer email
          # committer_email: # optional, default is 41898282+github-actions[bot]@users.noreply.github.com
          # Committer name
          # committer_name: # optional, default is github-actions[bot]
          # If true, no changes will be made to the repo
          # dryrun: # optional
